#!/bin/bash
set -euo pipefail
if [ "$EUID" -ne 0 ]; then
  echo "Run with sudo: sudo ./install.sh"
  exit 1
fi

VERSION="$(tr -d '[:space:]' < VERSION)"
APP_ROOT=/opt/feednode
RELEASE="$APP_ROOT/releases/$VERSION"
STATE=/var/lib/feednode

printf '\nFeedNode %s replacement install\n' "$VERSION"

# Stop the current display/app before replacing release files.
systemctl stop feednode-kiosk.service >/dev/null 2>&1 || true
systemctl stop feednode-splash.service >/dev/null 2>&1 || true
systemctl stop feednode.service >/dev/null 2>&1 || true
apt purge -y cage cog chromium chromium-browser openbox xserver-xorg xinit unclutter >/dev/null 2>&1 || true

apt update
apt install -y \
  python3-venv python3-pip \
  network-manager avahi-daemon curl \
  python3-pygame libegl-dev fonts-dejavu-core libpam-systemd

systemctl enable --now NetworkManager

if id feednode >/dev/null 2>&1; then
  usermod -aG video,render,input feednode
else
  useradd -m -s /bin/bash -G video,render,input feednode
fi

mkdir -p "$APP_ROOT/releases" "$STATE"/{config,credentials,cache} /etc/feednode
rm -rf "$RELEASE"
mkdir -p "$RELEASE"
cp app.py app_wrapper.py display.py stats_display.py requirements.txt config.default.json VERSION "$RELEASE"/
cp -r config static templates scripts updater "$RELEASE"/
ln -sfn "$RELEASE" "$APP_ROOT/current"

if [ -d "$APP_ROOT/venv" ]; then
  rm -rf "$APP_ROOT/venv"
fi
python3 -m venv --system-site-packages "$APP_ROOT/venv"
"$APP_ROOT/venv/bin/pip" install --upgrade pip
"$APP_ROOT/venv/bin/pip" install -r "$RELEASE/requirements.txt"

[ -f "$STATE/config/config.json" ] || cp "$RELEASE/config.default.json" "$STATE/config/config.json"
chown -R feednode:feednode "$APP_ROOT" "$STATE" /home/feednode

install -m 755 "$RELEASE/scripts/feednode-network" /usr/local/bin/feednode-network
install -m 755 "$RELEASE/scripts/feednode-reset" /usr/local/bin/feednode-reset
install -m 755 "$RELEASE/scripts/firstboot-network" /usr/local/bin/feednode-firstboot-network
install -m 755 "$RELEASE/scripts/kiosk.sh" /usr/local/bin/feednode-kiosk
install -m 755 "$RELEASE/scripts/boot-splash.sh" /usr/local/bin/feednode-boot-splash
install -m 644 services/feednode.service /etc/systemd/system/feednode.service
install -m 644 services/feednode-network.service /etc/systemd/system/feednode-network.service
install -m 644 services/feednode-splash.service /etc/systemd/system/feednode-splash.service
install -m 644 services/feednode-kiosk.service /etc/systemd/system/feednode-kiosk.service
install -m 644 services/feednode-updater.service /etc/systemd/system/feednode-updater.service
install -m 644 services/feednode-updater.timer /etc/systemd/system/feednode-updater.timer

cat >/etc/sudoers.d/feednode <<'SUDO'
feednode ALL=(root) NOPASSWD: /usr/local/bin/feednode-network, /usr/local/bin/feednode-reset, /opt/feednode/current/scripts/update.sh *, /usr/bin/systemctl restart feednode-kiosk.service, /usr/bin/systemctl reboot, /usr/bin/systemd-run --unit=feednode-firmware-update --collect /opt/feednode/venv/bin/python /opt/feednode/current/updater/updater.py install
SUDO
chmod 440 /etc/sudoers.d/feednode

if [ ! -f /etc/feednode/feednode.env ]; then
cat >/etc/feednode/feednode.env <<'ENV'
# Optional developer overrides. Normal end users do not edit this file.
TWITCH_CLIENT_ID=
FEEDNODE_GITHUB_REPO=iamvinyl/FeedNode
# Required for firmware checks when the GitHub repository is private.
FEEDNODE_GITHUB_TOKEN=
ENV
chmod 640 /etc/feednode/feednode.env
chown root:feednode /etc/feednode/feednode.env
else
  grep -q '^FEEDNODE_GITHUB_REPO=' /etc/feednode/feednode.env || echo 'FEEDNODE_GITHUB_REPO=iamvinyl/FeedNode' >> /etc/feednode/feednode.env
  if ! grep -q '^FEEDNODE_GITHUB_TOKEN=' /etc/feednode/feednode.env; then
    printf '\n# Required for firmware checks when the GitHub repository is private.\nFEEDNODE_GITHUB_TOKEN=\n' >> /etc/feednode/feednode.env
  fi
fi

# Make HDMI boot look like an appliance instead of exposing the Linux console.
CMDLINE_FILE=""
if [ -f /boot/firmware/cmdline.txt ]; then
  CMDLINE_FILE=/boot/firmware/cmdline.txt
elif [ -f /boot/cmdline.txt ]; then
  CMDLINE_FILE=/boot/cmdline.txt
fi
if [ -n "$CMDLINE_FILE" ]; then
  for arg in quiet loglevel=0 systemd.show_status=false rd.systemd.show_status=false vt.global_cursor_default=0 logo.nologo; do
    if ! grep -qw "$arg" "$CMDLINE_FILE"; then
      sed -i "1 s|$| $arg|" "$CMDLINE_FILE"
    fi
  done
fi

BOOT_CONFIG=""
if [ -f /boot/firmware/config.txt ]; then
  BOOT_CONFIG=/boot/firmware/config.txt
elif [ -f /boot/config.txt ]; then
  BOOT_CONFIG=/boot/config.txt
fi
if [ -n "$BOOT_CONFIG" ] && ! grep -Eq '^disable_splash=1$' "$BOOT_CONFIG"; then
  printf '\n# FeedNode appliance boot\ndisable_splash=1\n' >> "$BOOT_CONFIG"
fi

systemctl daemon-reload
systemctl disable --now getty@tty1.service >/dev/null 2>&1 || true
systemctl enable feednode-network.service
systemctl enable feednode-splash.service
systemctl enable --now feednode.service
systemctl enable --now feednode-kiosk.service
systemctl enable --now feednode-updater.timer
hostnamectl set-hostname feednode
systemctl enable --now avahi-daemon

printf '\nFeedNode %s installed.\n' "$VERSION"
printf 'Settings: http://feednode.local:8787/settings\n'
printf 'HDMI: FeedNode loading splash -> native pygame/SDL2 KMSDRM renderer\n'
printf 'Existing Wi-Fi, layout settings, and Twitch credentials were preserved.\n'
printf 'If Twitch was already authorized, EventSub will start automatically.\n'
printf 'For private-repo firmware updates, set FEEDNODE_GITHUB_TOKEN in /etc/feednode/feednode.env.\n'
printf 'Reboot once to apply the quiet HDMI boot screen.\n\n'
