#!/bin/bash
set -euo pipefail
if [ "$EUID" -ne 0 ]; then
  echo "Run with sudo: sudo ./install.sh"
  exit 1
fi

VERSION="$(tr -d '[:space:]' < VERSION)"
APP_ROOT=/opt/feednode
RELEASE="$APP_ROOT/releases/$VERSION"
STATE=/var/lib/feednode

printf '\nFeedNode %s replacement install\n' "$VERSION"

# Stop the current display/app before replacing release files.
systemctl stop feednode-kiosk.service >/dev/null 2>&1 || true
systemctl stop feednode.service >/dev/null 2>&1 || true
apt purge -y cage cog chromium chromium-browser openbox xserver-xorg xinit unclutter >/dev/null 2>&1 || true

apt update
apt install -y \
  python3-venv python3-pip \
  network-manager avahi-daemon curl \
  python3-pygame libegl-dev fonts-dejavu-core libpam-systemd

systemctl enable --now NetworkManager

if id feednode >/dev/null 2>&1; then
  usermod -aG video,render,input feednode
else
  useradd -m -s /bin/bash -G video,render,input feednode
fi

mkdir -p "$APP_ROOT/releases" "$STATE"/{config,credentials,cache} /etc/feednode
rm -rf "$RELEASE"
mkdir -p "$RELEASE"
cp app.py display.py requirements.txt config.default.json VERSION "$RELEASE"/
cp -r config static templates scripts updater "$RELEASE"/
ln -sfn "$RELEASE" "$APP_ROOT/current"

if [ -d "$APP_ROOT/venv" ]; then
  rm -rf "$APP_ROOT/venv"
fi
python3 -m venv --system-site-packages "$APP_ROOT/venv"
"$APP_ROOT/venv/bin/pip" install --upgrade pip
"$APP_ROOT/venv/bin/pip" install -r "$RELEASE/requirements.txt"

[ -f "$STATE/config/config.json" ] || cp "$RELEASE/config.default.json" "$STATE/config/config.json"
chown -R feednode:feednode "$APP_ROOT" "$STATE" /home/feednode

install -m 755 "$RELEASE/scripts/feednode-network" /usr/local/bin/feednode-network
install -m 755 "$RELEASE/scripts/feednode-reset" /usr/local/bin/feednode-reset
install -m 755 "$RELEASE/scripts/firstboot-network" /usr/local/bin/feednode-firstboot-network
install -m 755 "$RELEASE/scripts/kiosk.sh" /usr/local/bin/feednode-kiosk
install -m 644 services/feednode.service /etc/systemd/system/feednode.service
install -m 644 services/feednode-network.service /etc/systemd/system/feednode-network.service
install -m 644 services/feednode-kiosk.service /etc/systemd/system/feednode-kiosk.service
install -m 644 services/feednode-updater.service /etc/systemd/system/feednode-updater.service
install -m 644 services/feednode-updater.timer /etc/systemd/system/feednode-updater.timer

cat >/etc/sudoers.d/feednode <<'SUDO'
feednode ALL=(root) NOPASSWD: /usr/local/bin/feednode-network, /usr/local/bin/feednode-reset, /opt/feednode/current/scripts/update.sh *
SUDO
chmod 440 /etc/sudoers.d/feednode

if [ ! -f /etc/feednode/feednode.env ]; then
cat >/etc/feednode/feednode.env <<'ENV'
# Optional developer overrides. Normal end users do not edit this file.
TWITCH_CLIENT_ID=
FEEDNODE_GITHUB_REPO=iamvinyl/FeedNode
ENV
chmod 640 /etc/feednode/feednode.env
chown root:feednode /etc/feednode/feednode.env
fi

systemctl daemon-reload
systemctl disable --now getty@tty1.service >/dev/null 2>&1 || true
systemctl enable feednode-network.service
systemctl enable --now feednode.service
systemctl enable --now feednode-kiosk.service
systemctl enable --now feednode-updater.timer
hostnamectl set-hostname feednode
systemctl enable --now avahi-daemon

printf '\nFeedNode %s installed.\n' "$VERSION"
printf 'Settings: http://feednode.local:8787/settings\n'
printf 'HDMI: native pygame/SDL2 KMSDRM renderer (no browser)\n'
printf 'Existing Wi-Fi, layout settings, and Twitch credentials were preserved.\n'
printf 'If Twitch was already authorized, EventSub will start automatically.\n\n'
